apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  labels:
    app: inventory-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: mikejacks/pizza-co-servers-inventory-service:latest
          imagePullPolicy: Always
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: pizza-co-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: pizza-co-config
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: pizza-co-config
                  key: POSTGRES_DB_NAME
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: pizza-co-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: pizza-co-config
                  key: POSTGRES_PORT
            - name: USE_ENV_FILE
              valueFrom:
                configMapKeyRef:
                  name: pizza-co-config
                  key: USE_ENV_FILE
          ports:
            - containerPort: 9100
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  selector:
    app: inventory-service
  ports:
    - protocol: TCP
      port: 9100
      targetPort: 9100
  sessionAffinity: None
  type: ClusterIP
